version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "kinoko123", "--user", "kinoko"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
